#!/bin/bash
xml2po -o mintdesktop.pot -m mallard usr/share/help/C/mintdesktop/*.page
xgettext --language=Python --keyword=_ --output=mintdesktop.pot --join-existing usr/lib/linuxmint/mintdesktop/mintdesktop.py generate_desktop_files
